version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.13-bionic
    working_directory: /work
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
      - run: golint -set_exit_status .
      - run: ineffassign .
      - run: GOOS=windows go build .
      - run: go build .
      - run: go test -race -v .
      - run: go vet .
      - run: |
          go build ./test/restart
          ./restart
      - run: |
          cd ./test/spf13
          cp main.go_ main.go
          cp root.go_ root.go
          go build .
          ./spf13 --config=.spf13.yml --loglevel=critical
workflows:
  version: 2
  main:
    jobs:
      - build
