version: 2
jobs:
  build:
    docker:
      - image: quay.io/cybozu/golang:1.11-bionic
    working_directory: /work
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: test -z "$(gofmt -s -l . | tee /dev/stderr)"
      - run: golint -set_exit_status .
      - run: GOOS=windows go build .
      - run: go build .
      - run: go test -race -v .
      - run: go vet .
      - run: go build ./test/restart
      - run: ./restart
